/** Static marketing routes included in sitemap.xml (excludes thank-you, API, etc.). */
export const STATIC_SITEMAP_ROUTES = [
  { path: "/", priority: 1, changeFrequency: "weekly" },
  { path: "/about", priority: 0.8, changeFrequency: "monthly" },
  { path: "/contact", priority: 0.8, changeFrequency: "monthly" },
  { path: "/portfolio", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog", priority: 0.9, changeFrequency: "daily" },
  { path: "/mobile-app-development", priority: 0.9, changeFrequency: "weekly" },
  { path: "/app-development", priority: 0.9, changeFrequency: "weekly" },
  { path: "/website-development", priority: 0.9, changeFrequency: "weekly" },
  { path: "/game-development", priority: 0.9, changeFrequency: "weekly" },
  { path: "/mvp", priority: 0.9, changeFrequency: "weekly" },
  { path: "/ar-development", priority: 0.8, changeFrequency: "monthly" },
  { path: "/vr-development", priority: 0.8, changeFrequency: "monthly" },
  { path: "/cloud", priority: 0.8, changeFrequency: "monthly" },
  { path: "/iot", priority: 0.8, changeFrequency: "monthly" },
  { path: "/ios", priority: 0.9, changeFrequency: "weekly" },
  { path: "/flutter", priority: 0.9, changeFrequency: "weekly" },
  { path: "/hire-flutter", priority: 0.9, changeFrequency: "weekly" },
  { path: "/react-native", priority: 0.9, changeFrequency: "weekly" },
  { path: "/cross-platform", priority: 0.9, changeFrequency: "weekly" },
  { path: "/apps-for-startup", priority: 0.8, changeFrequency: "monthly" },
  { path: "/staff-augmentation", priority: 0.9, changeFrequency: "weekly" },
  { path: "/ecommerce", priority: 0.8, changeFrequency: "monthly" },
  { path: "/retail", priority: 0.8, changeFrequency: "monthly" },
  { path: "/erp", priority: 0.8, changeFrequency: "monthly" },
  { path: "/products", priority: 0.7, changeFrequency: "monthly" },
  { path: "/privacy-policy", priority: 0.3, changeFrequency: "yearly" },
  { path: "/terms-conditions", priority: 0.3, changeFrequency: "yearly" },
];
